version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - powerball-network
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5001:5001"
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://powerball:powerball@db:5432/powerball
      - DEBUG_NO_FALLBACK=false
      - PORT=5001
      - LOG_LEVEL=debug
      - SECRET_KEY=powerball_secret_key_change_in_production
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=powerball_admin
      - ADMIN_EMAIL=admin@example.com
      - ENABLE_SCHEDULER=true
      - CORS_ORIGINS=http://localhost,http://frontend,http://127.0.0.1
    depends_on:
      db:
        condition: service_healthy
    networks:
      - powerball-network
    volumes:
      - backend-data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/health"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    command: ["python", "main.py"]

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=powerball
      - POSTGRES_PASSWORD=powerball
      - POSTGRES_DB=powerball
    ports:
      - "5432:5432"
    networks:
      - powerball-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U powerball -d powerball"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=powerball
    ports:
      - "5050:80"
    networks:
      - powerball-network
    depends_on:
      - db
    restart: unless-stopped

networks:
  powerball-network:
    driver: bridge

volumes:
  backend-data:
  postgres-data:
    name: powerball_postgres_data